### ISSUE TITLE
FSLeyes cmaps invalid

### ISSUE THREAD

**Issue by pauldmccarthy** [CPernet/brain_colours#1]
Hey @CPernet !

I think an error has been made in generating the FSLeyes `.cmap` files - they appear to be in this format:
```
r r r
r r r
...
g g g
g g g
...
b b b
b b b
```

But they need to be in this format:

```
r g b
r g b
r g b
...
```

**Comment by CPernet** [comment]
weird, somehow the print function transposed value - should be fixed now?

**Comment by pauldmccarthy** [comment]
Looks much better, thanks! I'll try and get these into the next FSLeyes release (although am tied up in other projects right now, so it may be a while).
